### ISSUE TITLE
Interview Michael

### ISSUE THREAD

**Issue by rlmckenney** [MTM6330-F18/final-ssass#1]

**Comment by steffensen** [comment]
Wait... Who is this teacher again?

**Comment by brau0060** [comment]
idk

**Comment by steffensen** [comment]
I don't know either man...

**Comment by stew0343** [comment]
Interview Michael Wednesday Nov 7 at 12:30pm in T232 (Arrive early)

**Comment by steffensen** [comment]
Questions? Hello...

**Comment by stew0343** [comment]
1. How long has he been teaching at Algonquin?
1a. How long has he been teaching with IMD?
2. What courses has he taught?
3. What's his favourite course to teach?
4. What schooling does he have? (Degrees, diplomas, etc)

And anything else you can think of that we would want on the site.

**Comment by stew0343** [comment]
We still need a photo for Michael

**Comment by syts0002** [comment]
![michael](https://user-images.githubusercontent.com/43067761/48450788-9e6e0380-e775-11e8-8a85-cd864175c226.jpg)

**Comment by syts0002** [comment]
Pulled from his police record.

**Comment by steffensen** [comment]
do we have a bigger picture of Michael?
