### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by stew0343** [MTM6330-F18/final-ssass#15]

**Comment by steffensen** [comment]
![imd](https://user-images.githubusercontent.com/40807050/48450017-821c9780-e772-11e8-8505-fbb7549cc647.png)

**Comment by steffensen** [comment]
![screen-logo](https://user-images.githubusercontent.com/40807050/48450045-aaa49180-e772-11e8-9cb4-6ec913d71d27.png)

**Comment by steffensen** [comment]
![imd-2](https://user-images.githubusercontent.com/40807050/48450388-f6a40600-e773-11e8-8791-0435827875d5.png)

**Comment by steffensen** [comment]
![screen-logo](https://user-images.githubusercontent.com/40807050/48450539-9b264800-e774-11e8-9bd9-0963eb4c6186.png)

**Comment by steffensen** [comment]
![keyboard3 1](https://user-images.githubusercontent.com/40807050/49179012-575c4280-f31f-11e8-8247-34739054f418.png)
![keyboard2](https://user-images.githubusercontent.com/40807050/49179015-588d6f80-f31f-11e8-9fa6-095ff86ea29c.png)
![keyboard 1](https://user-images.githubusercontent.com/40807050/49179016-59be9c80-f31f-11e8-8a08-348487516c1c.png)

**Comment by steffensen** [comment]
![keyboard3 1](https://user-images.githubusercontent.com/40807050/49179046-6b07a900-f31f-11e8-90ea-fd25f369b9a0.png)

**Comment by steffensen** [comment]
![keyboard2](https://user-images.githubusercontent.com/40807050/49179072-79ee5b80-f31f-11e8-82fe-6bb6755b0be5.png)
