### ISSUE TITLE
Interview Abhay

### ISSUE THREAD

**Issue by stew0343** [MTM6330-F18/final-ssass#2]

**Comment by stew0343** [comment]
1. How long has he been teaching at Algonquin?
1a. How long has he been teaching with IMD?
2. What courses has he taught?
3. What's his favourite course to teach?
4. What schooling does he have? (Degrees, diplomas, etc)

And anything else you can think of that we would want on the site.

**Comment by steffensen** [comment]
Waiting on Anhay to send me a headshot

**Comment by stew0343** [comment]
Do we have a headshot for Abhay yet?

**Comment by steffensen** [comment]
Nope

**Comment by steffensen** [comment]
![img_6121](https://user-images.githubusercontent.com/40807050/48676587-b1e2eb00-eb36-11e8-82cc-dfc3ed49efb9.jpg)
