### ISSUE TITLE
Create branding guide

### ISSUE THREAD

**Issue by stew0343** [MTM6330-F18/final-ssass#20]

**Comment by alia0021** [comment]
![brading guide](https://user-images.githubusercontent.com/43006219/48293635-183c7f00-e44e-11e8-9187-a3bcd6d2f441.png)

**Comment by steffensen** [comment]
![branding](https://user-images.githubusercontent.com/40807050/48462400-0e947d80-e7a6-11e8-9d3b-4b6cf866d3d1.jpg)
