### ISSUE TITLE
Mobile wireframes

### ISSUE THREAD

**Issue by stew0343** [MTM6330-F18/final-ssass#4]

**Comment by alia0021** [comment]
![course-page-4](https://user-images.githubusercontent.com/43006219/48294637-8fc0dd00-e453-11e8-8232-cc71cb2fa59a.png)
![course-page](https://user-images.githubusercontent.com/43006219/48294638-8fc0dd00-e453-11e8-9556-85add1f60cb7.png)
![course-page2](https://user-images.githubusercontent.com/43006219/48294640-8fc0dd00-e453-11e8-866d-c54f63df1f52.png)
![course-page3](https://user-images.githubusercontent.com/43006219/48294641-90597380-e453-11e8-8671-e7c05f421e48.png)
![overview](https://user-images.githubusercontent.com/43006219/48294642-90597380-e453-11e8-96d7-a340f67fd790.png)
![topic of interest](https://user-images.githubusercontent.com/43006219/48294643-90597380-e453-11e8-90a0-e48709027352.png)

**Comment by alia0021** [comment]
![landing-page](https://user-images.githubusercontent.com/43006219/48294655-a0715300-e453-11e8-92a7-93eadee12e92.png)

**Comment by steffensen** [comment]
![iphone 5-se 1](https://user-images.githubusercontent.com/40807050/48462428-2ec43c80-e7a6-11e8-9f1b-4bb5e5da4d85.jpg)
![level 01](https://user-images.githubusercontent.com/40807050/48462429-2ec43c80-e7a6-11e8-9e5b-8dd577697da2.jpg)
![level 02](https://user-images.githubusercontent.com/40807050/48462430-2f5cd300-e7a6-11e8-9218-93d666826c91.jpg)
![level 03](https://user-images.githubusercontent.com/40807050/48462431-2f5cd300-e7a6-11e8-9165-5b2ead82bc4d.jpg)
![level 04](https://user-images.githubusercontent.com/40807050/48462432-2f5cd300-e7a6-11e8-9dd5-f84feab43082.jpg)
![mobile - home](https://user-images.githubusercontent.com/40807050/48462433-2f5cd300-e7a6-11e8-8a15-faa16472b808.jpg)
![our program](https://user-images.githubusercontent.com/40807050/48462434-2f5cd300-e7a6-11e8-8bd1-7504644787bc.jpg)
![teacher discription](https://user-images.githubusercontent.com/40807050/48462435-2f5cd300-e7a6-11e8-97bc-1ab0ca625fb4.jpg)
![teacher](https://user-images.githubusercontent.com/40807050/48462437-2f5cd300-e7a6-11e8-885c-d080c694a98c.jpg)
![interests](https://user-images.githubusercontent.com/40807050/48462439-2f5cd300-e7a6-11e8-88fe-9d630d2b36a8.jpg)

**Comment by steffensen** [comment]
![level 01](https://user-images.githubusercontent.com/40807050/49390583-606e5a80-f6f7-11e8-955e-ccc68c9c867c.png)
![our program](https://user-images.githubusercontent.com/40807050/49390584-619f8780-f6f7-11e8-97f2-a0a144d2793f.png)
![overview](https://user-images.githubusercontent.com/40807050/49390586-62d0b480-f6f7-11e8-83fa-d6631e116250.png)
![schedule](https://user-images.githubusercontent.com/40807050/49390601-66fcd200-f6f7-11e8-9d5e-4c9ef1172498.png)
![teacher discription](https://user-images.githubusercontent.com/40807050/49390602-66fcd200-f6f7-11e8-88a4-c3b1cc4fea3f.png)
![teacher](https://user-images.githubusercontent.com/40807050/49390603-67956880-f6f7-11e8-810a-d0dc45643274.png)
Updated Versions

**Comment by steffensen** [comment]
![our program](https://user-images.githubusercontent.com/40807050/49390745-c1962e00-f6f7-11e8-84eb-4b7c5afd5f1c.png)
