### ISSUE TITLE
Tablet wireframes

### ISSUE THREAD

**Issue by stew0343** [MTM6330-F18/final-ssass#5]

**Comment by alia0021** [comment]
![course-tablet](https://user-images.githubusercontent.com/43006219/48294624-71f37800-e453-11e8-89bf-d4a23d155cf8.png)
![landing-tablet](https://user-images.githubusercontent.com/43006219/48294625-71f37800-e453-11e8-9ead-d230d9c96ebc.png)
![overview-tablet](https://user-images.githubusercontent.com/43006219/48294626-71f37800-e453-11e8-868b-a524e6124a29.png)
![topicofinterest-tablet](https://user-images.githubusercontent.com/43006219/48294627-71f37800-e453-11e8-94e1-3e5ea2b559fd.png)
