### ISSUE TITLE
Desktop wireframes

### ISSUE THREAD

**Issue by stew0343** [MTM6330-F18/final-ssass#6]

**Comment by alia0021** [comment]
Tyler, I'm going to send you svgs for the mockups so that you can upload them on ai and edit them from there.

**Comment by alia0021** [comment]
@steffensen  I'm going to send you svgs for the mockups so that you can upload them on ai and edit them from there.

**Comment by alia0021** [comment]
![course-desktop](https://user-images.githubusercontent.com/43006219/48294614-4ff9f580-e453-11e8-816c-86287ca0ea82.png)
![landing-desktop](https://user-images.githubusercontent.com/43006219/48294615-4ff9f580-e453-11e8-9f21-2b34d26dc029.png)
![overview-desktop](https://user-images.githubusercontent.com/43006219/48294616-50928c00-e453-11e8-8a40-d95689afaae7.png)
![Uploading topicofinterestdesktop.png…]()

**Comment by steffensen** [comment]
![web 1920 1](https://user-images.githubusercontent.com/40807050/48462469-4a2f4780-e7a6-11e8-9be7-86595866364c.jpg)
![web 1920 2](https://user-images.githubusercontent.com/40807050/48462470-4a2f4780-e7a6-11e8-8153-55698b8989ce.jpg)
![home - desktop](https://user-images.githubusercontent.com/40807050/48462471-4a2f4780-e7a6-11e8-93a7-b1620cf30f49.jpg)
![interest](https://user-images.githubusercontent.com/40807050/48462472-4a2f4780-e7a6-11e8-8724-3459a3e71d09.jpg)
![level -1](https://user-images.githubusercontent.com/40807050/48462473-4a2f4780-e7a6-11e8-832a-a466f1d3f1d2.jpg)
![overview](https://user-images.githubusercontent.com/40807050/48462474-4a2f4780-e7a6-11e8-836d-25af5a134bdb.jpg)

**Comment by steffensen** [comment]
![overview](https://user-images.githubusercontent.com/40807050/49390498-1e451900-f6f7-11e8-9d29-2a07fbc89833.png)
![interest](https://user-images.githubusercontent.com/40807050/49390501-200edc80-f6f7-11e8-9651-09462141ce3e.png)
![level -1](https://user-images.githubusercontent.com/40807050/49390507-24d39080-f6f7-11e8-9181-2462a0fc9dbf.png)
![web 1920 2](https://user-images.githubusercontent.com/40807050/49390519-2d2bcb80-f6f7-11e8-97d1-c6bde8cc7a1e.png)
Updated Versions
